// client-react/src/components/TaskList.js
import React from 'react';
import * as moment from 'moment';
import { Table } from 'react-bootstrap';

function TaskList ({ tasks }) {
  const DEFAULT_DATETIME_FORMAT = 'MMMM Do YYYY, h:mm:ss a';
  const classNameByStatus = {
    SUCCESS: 'table-success',
    FAILURE: 'table-error',
    PENDING: 'table-info'
  };
  let tableBody;

  if (tasks.length === 0) {
    tableBody = <tr><td className='text-center' colSpan='4'>No tasks.</td></tr>
  } else {
    tableBody = tasks.map(task => {
      const className = classNameByStatus[task.status];
      return <tr className={className} key={task.id}>
        <th scope='row'>{task.id}</th>
        <td>{task.status}</td>
        <td>{moment(task.created).format(DEFAULT_DATETIME_FORMAT)}</td>
        <td>{moment(task.updated).format(DEFAULT_DATETIME_FORMAT)}</td>
      </tr>
    })
  }

  return (
    <>
      <h2>Tasks</h2>
      <Table>
        <thead>
          <tr>
            <th scope='col'>ID</th>
            <th scope='col'>Status</th>
            <th scope='col'>Created</th>
            <th scope='col'>Updated</th>
          </tr>
        </thead>
        <tbody>
          {tableBody}
        </tbody>
      </Table>
    </>
  );
}

export default TaskList;

// client-vue/src/components/TaskList.vue
<template>
<fragment>
  <h2>Tasks</h2>
  <b-table-simple>
    <b-thead>
      <b-tr>
        <b-th scope='col'>ID</b-th>
        <b-th scope='col'>Status</b-th>
        <b-th scope='col'>Created</b-th>
        <b-th scope='col'>Updated</b-th>
      </b-tr>
    </b-thead>
    <b-tbody v-if='tasks.length > 0'>
      <task-list-row v-for='task in tasks' :key='task.id' v-bind:task='task' />
    </b-tbody>
    <b-tbody v-if='tasks.length === 0'>
      <b-tr>
        <b-td class='text-center' colspan='4'>No tasks.</b-td>
      </b-tr>
    </b-tbody>
  </b-table-simple>
</fragment>
</template>

<script>
import { Fragment } from 'vue-fragment'
import TaskListRow from './TaskListRow'
export default {
  name: 'TaskList',
  components: { Fragment, TaskListRow },
  props: {
    tasks: Array
  }
}
</script>
