// client-vue/src/App.vue
<template>
<b-container id='app' class='pt-3'>
  <b-row>
    <b-col>
      <task-form @clear-tasks='clearTasks' @create-task='createTask' />
    </b-col>
    <b-col>
      <task-list v-bind:tasks='tasks' />
    </b-col>
  </b-row>
</b-container>
</template>

<script>
import axios from 'axios'
import TaskForm from './components/TaskForm'
import TaskList from './components/TaskList'
export default {
  name: 'App',
  components: { TaskForm, TaskList },
  data: function () {
    return {
      intervalId: 0,
      socket: undefined,
      tasks: []
    }
  },
  created: async function () {
    const response = await axios.get('/tasks/')
    this.tasks = response.data
    this.socket = new WebSocket('ws://localhost:8080/tasks/')
    this.socket.addEventListener('message', this.onMessage)
  },
  destroyed: function () {
    clearInterval(this.intervalId)
    if (this.socket) {
      this.socket.removeEventListener('message')
      this.socket.close()
    }
  },
  methods: {
    clearTasks: async function () {
      const response = await axios.post('/tasks/clear/')
      this.$toasted.error(response.data.detail)
      this.tasks = []
    },
    createTask: async function (duration, sync) {
      const response = await axios.post('/tasks/', { duration: parseInt(duration), sync })
      const task = response.data
      this.tasks.push(task)
      if (sync) {
        clearInterval(this.intervalId)
        this.intervalId = setInterval(async () => {
          this.$toasted.show('Are you done yet?')
          const response = await axios.get(`/tasks/${task.id}/`)
          this.tasks.pop()
          this.tasks.push(response.data)
          if (response.data.status !== 'PENDING') {
            clearInterval(this.intervalId)
            this.$toasted.success('I\'m done.')
          }
        }, 1000);
      } else {
        const group = `task-${task.id}`;
        this.socket.send(JSON.stringify({ group }));
      }
    },
    onMessage: function (event) {
      const message = JSON.parse(event.data)
      if ('task' in message) {
        this.tasks.pop()
        this.tasks.push(message.task)
        this.$toasted.success('I\'m done.'); 
      } else if ('detail' in message) {
        this.$toasted.show('Pending...');
      } else {
        console.log(message);
      }
    }
  }
}
</script>

// client-react/src/App.js
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Col, Container, Row } from 'react-bootstrap';
import { ToastContainer, toast } from 'react-toastify';

import './App.css';

import TaskForm from './components/TaskForm';
import TaskList from './components/TaskList';

const socket = new WebSocket('ws://localhost:8080/tasks/');

function App () {
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    const onMessage = (event) => {
      const message = JSON.parse(event.data);
      if (message.hasOwnProperty('task')) {
        setTasks(oldTasks => {
          const newTasks = [...oldTasks];
          newTasks[newTasks.length - 1] = message.task;
          return newTasks;
        });
        toast.success('I\'m done.'); 
      } else if (message.hasOwnProperty('detail')) {
        toast.info('Pending...');
      } else {
        console.log(message);
      }
    };
    socket.addEventListener('message', onMessage);
    return () => {
      socket.close();
    }
  }, []);

  useEffect(() => {
    const listTasks = async () => {
      const response = await axios.get('/tasks/');
      setTasks(response.data);
    };
    listTasks();
  }, []);

  let intervalId = 0;

  const clearTasks = async () => {
    const response = await axios.post('/tasks/clear/');
    toast.warn(response.data.detail);
    setTasks([]);
  };

  const createTask = async (duration, sync) => {
    const response = await axios.post('/tasks/', { duration, sync });
    const task = response.data;
    setTasks(prevTasks => [...prevTasks, task]);
    if (sync) {
      clearInterval(intervalId);
      intervalId = setInterval(async () => {
        toast.info('Are you done yet?');
        const response = await axios.get(`/tasks/${task.id}/`);
        setTasks(oldTasks => {
          const newTasks = [...oldTasks];
          newTasks[newTasks.length - 1] = response.data;
          return newTasks;
        });
        if (response.data.status !== 'PENDING') {
          clearInterval(intervalId);
          toast.success('I\'m done.');
        }
      }, 1000);
    } else {
      const group = `task-${task.id}`;
      socket.send(JSON.stringify({ group }));
    }
  };

  return (
    <>
      <Container className='pt-3'>
        <Row>
          <Col>
            <TaskForm clearTasks={clearTasks} createTask={createTask} />
          </Col>
          <Col>
            <TaskList tasks={tasks} />
          </Col>
        </Row>
      </Container>
      <ToastContainer autoClose={1500} />
    </>
  );
}

export default App;
